# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[7, 9, 2, 9, 3, 6, 4, 5, 0, 9, 6, 0],
       [7, 7, 8, 6, 4, 0, 7, 8, 9, 1, 7, 2],
       [6, 2, 1, 2, 2, 2, 0, 4, 6, 5, 8, 3],
       [7, 8, 5, 0, 7, 0, 3, 5, 4, 1, 8, 7],
       [5, 1, 8, 4, 2, 2, 3, 5, 9, 3, 2, 1],
       [3, 3, 7, 9, 2, 9, 5, 1, 0, 8, 2, 4],
       [6, 4, 6, 1, 4, 4, 9, 2, 2, 0, 6, 4],
       [5, 2, 0, 8, 3, 5, 6, 9, 5, 2, 3, 5],
       [3, 7, 2, 2, 9, 5, 5, 8, 5, 4, 3, 6],
       [1, 2, 3, 7, 2, 9, 8, 5, 5, 0, 7, 7],
       [5, 2, 2, 5, 5, 9, 2, 6, 9, 7, 2, 0],
       [6, 8, 0, 8, 0, 0, 8, 0, 7, 1, 0, 9]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[7, 9, 2, 9, 3, 6, 4, 5, 0, 9, 6, 0],
       [7, 7, 8, 6, 4, 0, 7, 8, 9, 1, 7, 2],
       [6, 2, 1, 2, 2, 2, 0, 4, 6, 5, 8, 3],
       [7, 8, 5, 0, 7, 0, 3, 5, 4, 1, 8, 7],
       [5, 1, 8, 4, 2, 2, 3, 5, 9, 3, 2, 1],
       [3, 3, 7, 9, 2, 9, 5, 1, 0, 8, 2, 4],
       [6, 4, 6, 1, 4, 4, 9, 2, 2, 0, 6, 4],
       [5, 2, 0, 8, 3, 5, 6, 9, 5, 2, 3, 5],
       [3, 7, 2, 2, 9, 5, 5, 8, 5, 4, 3, 6],
       [1, 2, 3, 7, 2, 9, 8, 5, 5, 0, 7, 7],
       [5, 2, 2, 5, 5, 9, 2, 6, 9, 7, 2, 0],
       [6, 8, 0, 8, 0, 0, 8, 0, 7, 1, 0, 9]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   2,  16,   1,   5, -19,  16,   7,  21, -26,  11,   0],
       [  0, -14, -13,  -1,  -7,   6, -16,  -3,   2,   4,   9,   0],
       [  0,  17,   3, -18,  24, -14,   4,   4,  -5, -16,  14,   0],
       [  0, -20,  15,  -3,  -7,  -6,  -3,   2,  24,  -8,  -6,   0],
       [  0,  -3,   2,  22, -16,  23,  -2,  -8, -20,  27, -12,   0],
       [  0,  -1,  12, -23,   6, -11,  19, -13,   1, -18,  15,   0],
       [  0,  -8, -18,  26, -14,   2,  -4,  15,   2,  -4,  -4,   0],
       [  0,  19,  -4, -18,  24,  -8,  -7,   8,  -2,   6,  -8,   0],
       [  0,  -5,  -1,  16, -22,  12,  11,  -7,   1, -23,  16,   0],
       [  0,  -9,  -2,  -2,   4,  20, -23,   8,  11,  16,  -6,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [18]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()